### PR TITLE
Feature/ensure absent config (Fixes #5)

### LINKED ISSUE #5: Unset a config key
We are using the mageconfigsync to roll out required config changes on all environments with our CI. However, sometimes we feel the need to to revert a previously set config key to a state in which is should be unset. Is there a hidden feature in the way to mark a feature as forced unset?

### PR DESCRIPTION
**Pull request by jappievw**
Optimized the console output of the `diff` and `load` commands to make the `null` values visible. This fixes #5.

### CODE REVIEW

**Comment by jappievw** [comment]
@punkstar can you review my PR?

**Comment by punkstar** [comment]
Hey, sorry for the delay.  Can you merge develop in (it's been updated to check run tests via travis) please?  Also, it could write some unit tests to cover this it would be great.

**Comment by jappievw** [comment]
No problem. Had some delay as well. I just merged develop back in. However, I'm running into some testing issues. In my `ant` environment the tests don't run. Do you also experience these difficulties?

```
$ mageconfigsync[feature/ensure-absent-config]$ ant -version
Apache Ant(TM) version 1.9.4 compiled on April 29 2014
$ mageconfigsync[feature/ensure-absent-config]$ ant
Buildfile: /Users/jaspervanwanrooy/development/mageconfigsync/build.xml

test-unit:
     [exec] The command attribute is deprecated.
     [exec] Please use the executable attribute and nested arg elements.

BUILD FAILED
/Users/jaspervanwanrooy/development/mageconfigsync/build.xml:18: exec doesn't support the "passthru" attribute

Total time: 0 seconds
```

**Comment by punkstar** [comment]
It's `phing`, not `ant` :)

**Comment by jappievw** [comment]
Haha, ok. Makes sense then. Do you have some more project specific testing guidelines? Will take a closer look tonight

**Pull request merged**
